name: dashboard_trottinette
description: Un tableau de bord pour trottinette électrique intelligente.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.0.0  # Communication Bluetooth avec ESP32
  fl_chart: ^0.70.2          # Graphiques pour vitesse et batterie
  geolocator: ^13.0.2        # Gestion du GPS
  local_auth: ^2.1.6         # Authentification biométrique
  provider: ^6.1.2           # Gestion d'état
  cupertino_icons: ^1.0.8    # Icônes pour iOS
  syncfusion_flutter_gauges: ^20.4.48
  shared_preferences: ^2.0.11
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

